name: Generate Paper PDFs
on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft and Preprint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # WGenerate Draft PDF using inara (LaTeX is built-in)
      - name: Build Draft PDF
        uses: ./.github/actions/openjournals-pdf
        with:
          journal: joss
          paper-path: paper/paper.md
          output-type: pdf

      # Upload the Draft PDF
      - name: Upload Draft PDF
        uses: actions/upload-artifact@v4
        with:
          name: draft-paper
          path: paper/paper.pdf

      # Generate Preprint LaTeX File (`paper.preprint.tex`)
      - name: Build Preprint LaTeX File
        uses: ./.github/actions/openjournals-pdf
        with:
          journal: joss
          paper-path: paper/paper.md
          output-type: preprint

      # Print files to verify `paper.preprint.tex` exists
      - name: List contents of paper/
        run: ls -lah paper/

      # Compile Preprint PDF using inara (Reusing Built-in LaTeX)
      - name: Compile Preprint PDF
        run: |
          docker run --rm -v $(pwd)/paper:/data openjournals/inara:latest bash -c "
          cd /data && \
          pdflatex paper.preprint.tex && \
          bibtex paper && \
          pdflatex paper.preprint.tex && \
          pdflatex paper.preprint.tex
          "

      # List final contents to check if `paper.preprint.pdf` exists
      - name: List final contents of paper/
        run: ls -lah paper/

      # Upload the Preprint PDF
      - name: Upload Preprint PDF
        uses: actions/upload-artifact@v4
        with:
          name: preprint-paper
          path: paper/paper.preprint.pdf
