name: Generate Paper PDFs
on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft and Preprint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Generate Draft PDF (Default Output)
      - name: Build Draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md

      # Generate Preprint PDF using the Inara Docker Image
      - name: Build Preprint PDF
        run: |
          docker run --rm -v $PWD:/data openjournals/inara:latest -o preprint paper/paper.md

      # Upload the Draft PDF as an Artifact
      - name: Upload Draft PDF
        uses: actions/upload-artifact@v4
        with:
          name: draft-paper
          path: paper/paper.pdf  # This should be the same directory as paper.md

      # Upload the Preprint PDF as an Artifact
      - name: Upload Preprint PDF
        uses: actions/upload-artifact@v4
        with:
          name: preprint-paper
          path: paper/paper-preprint.pdf  # Ensure this matches the output filename
