name: Generate Paper PDFs
on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft and Preprint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ✅ Generate Draft PDF
      - name: Build Draft PDF
        uses: ./.github/actions/openjournals-pdf
        with:
          journal: joss
          paper-path: paper/paper.md
          output-type: pdf

      # ✅ Upload the Draft PDF
      - name: Upload Draft PDF
        uses: actions/upload-artifact@v4
        with:
          name: draft-paper
          path: paper/paper.pdf

      # ✅ Generate Preprint LaTeX File (Creates `paper.preprint.tex`)
      - name: Build Preprint (Generates .tex)
        uses: ./.github/actions/openjournals-pdf
        with:
          journal: joss
          paper-path: paper/paper.md
          output-type: preprint

      # ✅ List contents to verify `paper.preprint.tex` exists
      - name: List contents of paper/
        run: ls -lah paper/

      # ✅ Compile Preprint PDF with BibTeX Support (Using LaTeX Docker)
      - name: Compile Preprint PDF with Citations
        run: |
          docker run --rm -v $(pwd)/paper:/data texlive/texlive bash -c "
          cd /data && \
          pdflatex paper.preprint.tex && \
          bibtex paper.preprint && \
          pdflatex paper.preprint.tex && \
          pdflatex paper.preprint.tex
          "

      # ✅ List final contents to check `paper.preprint.pdf`
      - name: List final contents of paper/
        run: ls -lah paper/

      # ✅ Upload the Preprint PDF
      - name: Upload Preprint PDF
        uses: actions/upload-artifact@v4
        with:
          name: preprint-paper
          path: paper/paper.preprint.pdf
