name: Generate Paper PDFs
on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft and Preprint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ✅ Generate Draft PDF using inara
      - name: Build Draft PDF
        uses: ./.github/actions/openjournals-pdf
        with:
          journal: joss
          paper-path: paper/paper.md
          output-type: pdf

      # ✅ Upload the Draft PDF
      - name: Upload Draft PDF
        uses: actions/upload-artifact@v4
        with:
          name: draft-paper
          path: paper/paper.pdf

      # ✅ Generate Preprint LaTeX File (`paper.preprint.tex`)
      - name: Build Preprint LaTeX File
        uses: ./.github/actions/openjournals-pdf
        with:
          journal: joss
          paper-path: paper/paper.md
          output-type: preprint

      # ✅ Print files to verify `paper.preprint.tex` exists
      - name: List contents of paper/
        run: ls -lah paper/

      # ✅ Upload the Preprint LaTeX file (`paper.preprint.tex`)
      - name: Upload Preprint LaTeX File
        uses: actions/upload-artifact@v4
        with:
          name: preprint-tex
          path: paper/paper.preprint.tex
